load('ext://cert_manager', 'deploy_cert_manager')

# use a local registry cache
default_registry(
    'localhost:5000',
    host_from_cluster='registry:5000'
)

# install cert manager
deploy_cert_manager(
    version='v1.11.0',
    load_to_kind=True,
    kind_cluster_name='capi-mgmt'
)

# capi version
cv='1.3.3'

# list capi components
components = {
    'capi': cv,
    'capi-kubeadm-bootstrap': cv,
    'capi-kubeadm-control-plane': cv,
}

# helm install for oci targets
for k in components:
    cmd="helm install {} --version {} --namespace {}-system --set providerArgs.clusterTopology=true --create-namespace oci://ghcr.io/fire-ant/{}".format(k,components[k],k,k)
    local_resource(k, cmd=cmd)

providers = {
    'capvc': '0.1.3',
}

# helm install for oci targets
for k in providers:
    cmd="helm install {} --version {} --namespace {}-system --set providerArgs.clusterTopology=true --create-namespace oci://ghcr.io/fire-ant/{}".format(k,providers[k],k,k)
    local_resource(k, cmd=cmd)
