apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: vcluster-quickstart
  namespace: capvc-system
spec: 
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: vcluster-quickstart
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: vcluster-quickstart
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: vcluster-quickstart
  namespace: capvc-system
spec:

  kubernetesVersion: "1.25"