---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cni: cilium
  name: lm-1
  namespace: capmvm-system
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 172.25.0.0/16
    services:
      cidrBlocks:
      - 172.26.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: lm-1-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: MicrovmCluster
    name: lm-1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: MicrovmCluster
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  name: lm-1
  namespace: capmvm-system
spec:
  controlPlaneEndpoint:
    host: 10.0.2.15
    port: 7443
  placement:
    staticPool:
      hosts:
      - controlplaneAllowed: true
        endpoint: 10.0.2.15:9000
  sshPublicKeys:
  - authorizedKeys: []
    user: root
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  name: lm-1-control-plane
  namespace: capmvm-system
spec:
  kubeadmConfigSpec:
    clusterConfiguration: {}
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          provider-id: microvm://{{ ds.meta_data.vm_host }}/{{ ds.meta_data.instance_id
            }}
    joinConfiguration:
      nodeRegistration:
        ignorePreflightErrors:
        - DirAvailable--etc-kubernetes-manifests
        kubeletExtraArgs:
          provider-id: microvm://{{ ds.meta_data.vm_host }}/{{ ds.meta_data.instance_id
            }}
    preKubeadmCommands:
    - mkdir -p /etc/kubernetes/manifests && ctr images pull ghcr.io/kube-vip/kube-vip:v0.4.0
      && ctr run --rm --net-host ghcr.io/kube-vip/kube-vip:v0.4.0 vip /kube-vip manifest
      pod --arp --interface $(ip -4 -j route list default | jq -r .[0].dev) --address
      172.16.20.16 --controlplane --leaderElection > /etc/kubernetes/manifests/kube-vip.yaml
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
      kind: MicrovmMachineTemplate
      name: lm-1-control-plane
  replicas: 1
  version: v1.23.5
