---
apiVersion: v1
kind: Namespace
metadata:
  name: capd-system
---
apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: InfrastructureProvider
metadata:
  name: docker
  namespace: capd-system
spec:
  version: v1.3.4
  manager:
    featureGates:
      ClusterTopology: true
  deployment:
    containers:
        - name: manager
          args:
            ClusterTopology: "true"