---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-kubeadm-control-plane-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-kubeadm-bootstrap-system
---
apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: CoreProvider
metadata:
  name: cluster-api
  namespace: capi-system
spec:
  version: v1.3.4
  manager:
    featureGates:
      ClusterResourceSet: true
      MachinePool: true
      ClusterTopology: true
      RuntimeSDK: false
  deployment:
    containers:
        - name: manager
          args:
            MachinePool: "true"
            ClusterResourceSet: "true"
            ClusterTopology: "true"
            RuntimeSDK: "false"
---
apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: ControlPlaneProvider
metadata:
  name: kubeadm
  namespace: capi-kubeadm-control-plane-system
spec:
  version: v1.3.4
  manager:
    featureGates:
      ClusterTopology: true
  deployment:
    containers:
        - name: manager
          args:
            ClusterTopology: "true"
---
apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: BootstrapProvider
metadata:
  name: kubeadm
  namespace: capi-kubeadm-bootstrap-system
spec:
  version: v1.3.4
  manager:
    featureGates:
      MachinePool: true
  deployment:
    containers:
        - name: manager
          args:
            MachinePool: "true"