load('ext://cert_manager', 'deploy_cert_manager')
load('ext://namespace', 'namespace_create')

# use a local registry cache
default_registry(
    'localhost:5000',
    host_from_cluster='registry:5000'
)

# install cert manager
deploy_cert_manager(
    version='v1.11.0',
    load_to_kind=True,
    kind_cluster_name='capi-mgmt'
)

# capi-operator version
components = {
    'capi-operator': 'v0.1.0',
}

# helm install for oci targets
for k in components:
    cmd="helm install {} --version {} --namespace capi-operator-system --create-namespace oci://ghcr.io/fire-ant/{}".format(k,components[k],k,k)
    local_resource(k, cmd=cmd)

namespace_create('capi-system')
namespace_create('capi-kubeadm-bootstrap-system')
namespace_create('capi-kubeadm-control-plane-system')
namespace_create('capd-system')

# crds for cluster api components
k8s_yaml("operator-crds.yaml")
